config/routes.rb
Rails.application.routes.draw do

get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :administrators
  resources :contatos
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  get 'store/index'
  get 'store/contatos'
  get 'store/empresa'
  get 'store/loja'
  get 'contatos/new'


  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  before_action :set_administrator, only: %i[ show edit update destroy ]

  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.order(:name)
  end

  # GET /administrators/1 or /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to login_url, 
        notice: "Administrator #{@administrator.name} was successfully created." }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrator_url,
      notice: "Administrator #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.require(:administrator).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br><br><br>
  <div class="container">
  <h2>Enter User Details:</h2>
  <hr>
  </div>
<div class="container">
  <div class="administrator">
    <%= form.label :name, 'Name:' %>
    <%= form.text_field :name, size: 40, class: "form-control" %>
  </div>

  <div class="administrator">
    <%= form.label :password, 'Password:' %>
    <%= form.password_field :password, size: 40, class: "form-control" %>
  </div>

  <div class="administrator">
    <%= form.label :password_confirmation, 'Confirm:' %>

    <%= form.password_field :password_confirmation,
                            id: :user_password_confirmation,
                            size: 40, class: "form-control" %>
    
  </div>
<br>
  <div class="administrator">
    <%= form.submit 'Register' %>
  </div>
<% end %>

</div>
</div>

<br><br><br>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
    <tr>
      <td><%= administrator.name %></td>
      <td><%= link_to 'Show', administrator %></td>
      <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
      <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>
<hr>

<br>
<%= link_to '<< Admin', admin_path %>
</div>
<br><br><br><br>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>