config/routes.rb
Rails.application.routes.draw do

get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :administrators
  resources :contatos
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  get 'store/index'
  get 'store/contatos'
  get 'store/empresa'
  get 'store/loja'
  get 'contatos/new'


  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
   has_one_attached :featured_image
   validates :title, :description, presence: true
   validates :title, uniqueness: true
   validates :price, numericality: { greater_than_or_equal_to: 0.01 }

   has_many :line_items
   before_destroy :ensure_not_referenced_by_any_line_item

 private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
 
  # GET /products or /products.json
  def index
    @products = Product.all.order(:title)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        puts @product.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :featured_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
<% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% product.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<br><br>
<div class="container">
  <h2>Products:</h2>
  <hr>
</div>
<div class="container">
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <br>
  <br>
  <div class="file">
    <label class="file-label">
      <%= form.file_field :featured_image, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Escolha a imagem de destaque…
        </span>
      </span>
    </label>
  </div>
  <br>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<br>
<div class="container">
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<% if notice %>
<aside id="notice"><%= notice %></aside>
<% end %>
<br><br><br><br><br>

<div class="container">
  <h1>Products:</h1>
  <hr>

  <table>
    <tfoot>
      <tr>
        <td colspan="3">
          <%= link_to 'New Product', new_product_path %>
        </td>
      </tr>
    </tfoot>
    <tbody>
      <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td class="image">
          <%= image_tag product.featured_image %>
        </td>

        <td class="description">
          <h1><%= product.title %></h1>
          <p>
            <%= truncate(strip_tags(product.description),
                         length: 80) %>
          </p>
        </td>

        <td class="actions">
          <ul>
            <li><%= link_to 'Show', product %></li>
            <li><%= link_to 'Edit', edit_product_path(product) %></li>
            <li>
              <%= link_to 'Destroy',
                           product, 
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
            </li>
          </ul>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to '<< Admin', admin_path %>
<hr>

app/views/products/new.html.erb
<div class="container">
    <h1>New Product</h1>

    <%= render 'form', product: @product %>
    <br>
    <%= link_to 'Back', products_path %>
    <hr><br>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<figure class="image is-3by1">
  <%= image_tag @product.featured_image %>
</figure>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
</div>